### PR TITLE
update for consistent creation of custom prescribed forcing

### PR DESCRIPTION
**Pull request by mvertens**
Changes needed along with cdeps0.12.56 to have robust implementation for customizing sst/prescribed-ice forcing data
Verified that ERP_Ln9_Vnuopc.f09_f09_mg17.F2000climo.cheyenne_intel.cam-outfrq9s was bfb with corresponding baseline in cesm2_3_alpha09c

### CODE REVIEW

**Comment by mvertens** [comment]
@dabail10 - the AMP folks really need this change for their current science. If you could review this as soon as you get a chance - I'd really appreciate it.

**Review by dabail10 — APPROVED** [review]
I'm away at a meeting this week. This looks fine, but I'm not going to be able to create a tag right away.

**Comment by dabail10** [comment]
This should not got to main. It goes into cice6_20211214_branch2.

**Comment by dabail10** [comment]
Oh wait. Sorry, I was confused. Main on CESM_CICE is the right place. I won't be able to make a tag right away though.

**Comment by mvertens** [comment]
@dabail10 - thanks so much - I really appreciate your quick response.  Let me know when you do have a tag - and I'll put together a branch for the cam folks.

**Comment by dabail10** [comment]
Are you able to tag this? I'm in the meeting all day, so might not get to it for awhile.

**Comment by mvertens** [comment]
@dabail10 - I'll tag it. Thanks.

**Comment by dabail10** [comment]
I was able to do the tag. cesm_cice6_2_0_27

Dave

**Comment by mvertens** [comment]
Thanks so much!!! Really appreciate it.

**Pull request merged**
