### PR TITLE
Remove manage externals

### PR DESCRIPTION
**Pull request by jedwards4b**
Remove the requirement for manage_externals.  Standalone CICE can now be checked out with
git clone 
git submodule update --init --recursive

### CODE REVIEW

**Comment by dabail10** [comment]
This looks good. Did you want to change it from a draft PR?

**Comment by jedwards4b** [comment]
Not yet - I'm still working on some support tools and we will have a discussion in the 1/9 cseg meeting.

**Comment by dabail10** [comment]
Is this ready now?

**Review by dabail10 — APPROVED** [review]

**Comment by jedwards4b** [comment]
@dabail10 we may need to revert this and wait until after the restart alarm tag.

**Pull request merged**
