### PR TITLE
add cice6 as an external CESM component

### PR DESCRIPTION
**Pull request by mvertens**
This PR needs changes must be accompanied by changes to CIME and the CESM Extnerals.cfg in order to now have cice6 be checked out in the components/cice6. There are several caveats for cice6 to now work as an external CESM component.

1. **CICE6 ONLY works with CMEPS and requires the nuopc cap**

2. **Creating a case**: As long as the cice5 code base in components/cice exists, all compsets that use cice6 MUST be referred to by the long name. This was the key assumption in bringing the cice6 code in. So to create a B1850 compset using cice6, you need to execute create_newcase as follows:
`./create_newcase --driver nuopc --compset 11850_CAM60_CLM50%BGC-CROP_CICE6_POP2%ECO_MOSART_CISM2%NOEVOLVE_WW3_SESP_BGC%BDRD --res f19_g17 --case b1850cice6 
`
3. **Creating a test:** for individual tests the caveat in (1) also applies. 
`./create_test SMS_Vnuopc_Ld5.f19_g17.1850_CAM60_CLM50%BGC-CROP_CICE6_POP2%ECO_MOSART_CISM2%NOEVOLVE_WW3_SESP_BGC%BDRD`

4. **Running the aux_cice6 testlist**:
A new testlist aux_cice6 has been introduced in the cice6 CESM wrapper layer and can be run via the following command:
`qcmd -- ./create_test --xml-category aux_cice6 --xml-machine cheyenne --xml-driver nuopc --test-id  cice6`

### CODE REVIEW

**Review by dabail10 — COMMENTED** [review]
This looks good.

**Comment by mvertens** [comment]
@dabail10 - I am currently working through all of the failed aux_cice6 tests and will remove the draft designation once I've sorted all of that out.

**Comment by dabail10** [comment]
Sounds good. Do the user_nl files need cice6 on them in the testmod_dirs?

**Comment by mvertens** [comment]
@dbailey10 - yes - and in the $CASEROOT. That's a good point - I need to fix the user_nl_cice files in testmods_dirs.
Also - can I remove the gx1v6 resolution from CICE6? Are we even supporting that anymore?

**Comment by dabail10** [comment]
I don't think we can remove gx1v6 yet. However, I agree that this is something to think about.

**Comment by mvertens** [comment]
@dabail10 - sounds good. I won't touch it.

**Review by dabail10 — COMMENTED** [review]
Looks good. Merging to CESM_CICE master.

**Pull request merged**
